# Application name and port configuration
spring.application.name=fraud-detection-service
server.port=8081

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3316/fraud_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway migration configuration
spring.flyway.enabled=true

# SQL initialization mode
spring.sql.init.mode=always

# Actuator endpoints configuration
management.endpoints.web.exposure.include=health,info,prometheus,env,configprops
management.endpoint.health.show-details=always

# Logging configuration
logging.level.com.amir.fraud_detection_service=INFO
